### PR TITLE
Update analysis-vignettes.md

### PR DESCRIPTION
**Pull request by mengchen18**
add Chen Meng's vignette

### CODE REVIEW

**Comment by aljabadi** [comment]
@mengchen18 can you please create a package from your analyses following the steps outlined in [here](https://github.com/BIRSBiointegration/Hackathon/blob/master/analysis-vignettes.md#how-to-deploy-your-own-html-and-containerized-report-using-github-actions). It will make it substantially easier to install the dependencies and reproduce the results for the purpose of the white paper and also for others.

**Comment by mengchen18** [comment]
Hi @ajabadi I have finished the package build but cannot get the docker push run through. Is it ok without a container file? Thanks for taking care of this.

**Comment by aljabadi** [comment]
Hi @mengchen18,

No worries. I'm glad your vignette is up and running.
 Can you just revert [this commit](https://github.com/mengchen18/BIRSBIO2020.scProteomics.predictPartialOverlappingData/commit/578790aa6cf470bf61a8a5bf296ac59e73e64983) and try the Docker push again? If the Docker credentials aren't the issue, it must have been a simple timeout as it had occurred before. The reason I believe so is that it worked on [my fork of your repo](https://github.com/ajabadi/BIRSBIO2020.scProteomics.predictPartialOverlappingData/commits/master) when I simply reactivated the push task and pushed to my own Docker.

If the problem insisted you can also check the popular solutions [here](https://github.com/docker/hub-feedback/issues/1222) and re-try.

Thanks

**Comment by aljabadi** [comment]
add Chen Meng's vignette

**Pull request merged**
