### PR TITLE
adding CV-MOFA vignette

### PR DESCRIPTION
**Pull request by mikelove**

### CODE REVIEW

**Comment by aljabadi** [comment]
Hi @mikelove. This does not seem to be reproducible.

**Comment by mikelove** [comment]
I just removed all hard coded paths. These were just pointing to files that are in the repository.

We won't be able to make the Rmd run from scratch on a fresh machine, but all the inputs and output are stored in the repo and all the code that was used in our benchmark is provided.

**Comment by aljabadi** [comment]
For consistency, I compiled the provided source code and output data files (the actual run is not being performed) to generate [this semi-automated vignette](https://ajabadi.github.io/BIRSBIO2020.Benchmarking.CVmofa/index.html). It would be great if you could make any changes you'd like, or let me know if you're happy to use this one. Obviously, having it run in full is even better.

**Comment by mikelove** [comment]
Thanks! This looks great!

**Pull request merged**
